apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: support-priority-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maieran/ArgoCD_Course
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: support-priority
  syncPolicy:
    automated: {}